### ISSUE TITLE
Please do not hard code colors into the extension but instead use themeable properties.

### ISSUE THREAD

**Issue by grymmjack** [QB64Official/vscode#119]
https://github.com/QB64Official/vscode/commit/51bb8ecf51b30f57abb1aa06fae94321a23e1d61#r113996771

I spent 30 minutes trying to override this in the theme. It's not over-rideable.
![image](https://github.com/QB64Official/vscode/assets/412263/ec9a6427-0d5f-41da-afc7-d1890361f038)

![image](https://github.com/QB64Official/vscode/assets/412263/6fde9a4c-cbc8-4628-a6d8-7ba81d115584)

Example returning a themeable color vs. hardcoded from
https://github.com/microsoft/vscode/issues/78660:

```
const vscode = require('vscode');

function activate(context) {
    var decorator = vscode.window.createTextEditorDecorationType( {
      color: new vscode.ThemeColor('editor.selectionForeground'),
      backgroundColor: new vscode.ThemeColor('editor.selectionBackground')
    });

    context.subscriptions.push(
        vscode.commands.registerCommand('extension.decoratorselect', () => {
            const editor = vscode.window.activeTextEditor;
            if (!editor) { return; }
            editor.setDecorations(decorator, [new vscode.Range(new vscode.Position(1, 0), new vscode.Position(1, 20))]);
        })
    );
};

function deactivate() {}

module.exports = {
    activate,
    deactivate
}
```

**Comment by LordDurus** [comment]
This is a good idea and will be done.

**Comment by LordDurus** [comment]
This is ready to text in v0.9.1

**Comment by grymmjack** [comment]
Tested and worked for the color, but now new issue with bold #120

**Comment by LordDurus** [comment]
Making this one done.
