### ISSUE TITLE
Please do not change the font style of anything by default

### ISSUE THREAD

**Issue by grymmjack** [QB64Official/vscode#120]
https://github.com/QB64Official/vscode/blob/3f6e6633a6d325d660b981a4bdbab245f59e64af/src/decoratorFunctions.ts#L95
https://github.com/QB64Official/vscode/blob/3f6e6633a6d325d660b981a4bdbab245f59e64af/src/decoratorFunctions.ts#L100

![image](https://github.com/QB64Official/vscode/assets/412263/5467e311-c219-405e-a33f-404ed6e3bb69)

We can instead use the `settings.json` and `"fontStyle": "bold"` in the `"settings"` block if bold is desired.

I cannot unset it, I have tried.

```json
    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    "userfunctions.QB64",
                    "entity.name.function.QB64",
                    "meta.function.QB64",
                    "source.QB64",
                    "entity.name.function"
                ],
                "settings": {
                    "fontStyle": ""
                }
            }
        ]
    }
```

The setting is working, just is bold by default which should not be forced on the user.

**Comment by LordDurus** [comment]
Agreed.  This and any new font styles should be controlled by a setting.

**Comment by LordDurus** [comment]
This is ready to test in dev.

**Comment by grymmjack** [comment]
The setting doesn't seem to work, and the highlighting does not factor int the return type variety:
![image](https://github.com/QB64Official/vscode/assets/412263/e40cf9af-97d4-4bab-bdc3-8b9b3ad09bc6)

I have in my settings:
```json
    "qb64.isBoldingSubsAndFunctionsEnabled": true,
```

And it's not bolded.

Note that a function that ends in a type suffix is also not matched.

**Comment by grymmjack** [comment]
Actually. I think it was the font rendering on the Mac. I was using my Mac.

On PC, it's absolutely working.

Sorry for the false info @LordDurus

**Comment by grymmjack** [comment]
There is a bug though. It looks like you need negative lookahead for `'` 
![image](https://github.com/QB64Official/vscode/assets/412263/0642cd79-5344-4623-993c-3edea5b61408)

See how it's highlighting the comment too?

**Comment by grymmjack** [comment]
Also some strange formatting here:
![image](https://github.com/QB64Official/vscode/assets/412263/3fa07f8e-8508-41b5-85a6-55cd6506b917)

**Comment by grymmjack** [comment]
Attaching the .BAS for these bugs for your own tests.
[MONEY.zip](https://github.com/QB64Official/vscode/files/11550476/MONEY.zip)

**Comment by grymmjack** [comment]
Another strange one:
![image](https://github.com/QB64Official/vscode/assets/412263/1a0a3e7b-d672-46dd-a88e-849cc0729a1c)

From my strings.bi here:
```basic
''
' QB64_GJ_LIB
' GRYMMJACK'S STRINGS LIB
'
' Some commonly used functions that I missed in QB64 coming from PHP
'
' USAGE:
'   Insert '$INCLUDE:'path_to_GJ_LIB/STRINGS/STRINGS.BI' at the top of file
'   Insert '$INCLUDE:'path_to_GJ_LIB/STRINGS/STRINGS.BM' at the bottom of file
' 
' @author Rick Christy <grymmjack@gmail.com>
' @uses STRINGS.BM
'
$LET GJ_LIB_STRINGS_INC_BI = 1
CONST GJ_LIB_MAX_STR_POSITIONS = 50



DECLARE FUNCTION str_implode$ (arr$(), delim$)
DECLARE SUB str_explode (target$, delim$, dest$(), numParts%)
DECLARE SUB str_find_pos (target$, search$, arrFound%(), numFound%)
DECLARE FUNCTION str_insert$ (s$, ins$, p%)
DECLARE FUNCTION str_remove$ (s$, del$)
DECLARE FUNCTION str_del (s$, del$)
DECLARE FUNCTION str_replace$ (s$, search$, replace$)
DECLARE FUNCTION str_rep$ (s$, search$, replace$)
DECLARE FUNCTION str_slice_pos (s$, startPos%, endPos%)

```

**Comment by grymmjack** [comment]
Last thing: good job on fixing the type suffixes on functions and subs highlighting. Works good:
![image](https://github.com/QB64Official/vscode/assets/412263/77c5bd40-8208-4bf1-aacf-30721ee0a761)

**Comment by LordDurus** [comment]
I think I have the issue with declare function fixed.   
The problem was the regex was matching function and not declare function.

**Comment by LordDurus** [comment]
Still need to fix:
![image](https://github.com/QB64Official/vscode/assets/2650021/b64f7dd7-0180-48ae-8fd3-6a40ce53f76e)

**Comment by LordDurus** [comment]
I think I have it working.  Let me know if you find anything else.

I pushed this to dev in v.0.9.1

**Comment by grymmjack** [comment]
Testing :)

**Comment by LordDurus** [comment]
Found another case of the comments getting highlighted (GOTO command)

![image](https://github.com/QB64Official/vscode/assets/2650021/658ad7ea-f320-47c0-9817-5fd2ba64cb06)

**Comment by LordDurus** [comment]
Took awhile, but looks good now
![image](https://github.com/QB64Official/vscode/assets/2650021/775f340f-d851-4a17-9a0d-1381f4e64bff)
