### ISSUE TITLE
No executable file for linux

### ISSUE THREAD

**Issue by danistheman360** [QB64Official/vscode#134]
In the linux (Im using debian tho...)  zip file, there is no release for linux. I still went ahead and used the .vsix extension... Now, when running code, I get "Permission denied" error when trying to run

**Comment by LordDurus** [comment]
The extension does not include the binaries.  There is a setting for the path to the binary make sure that is set.  It's in the QB64 section of the settings.

If that is set then there could be a different issue.  Let me know.

**Comment by danistheman360** [comment]
Please take me through the settings as I can't find help anywhere else. (I use a Linux debian on a Chromebook)

**Comment by LordDurus** [comment]
I'm using Zorin OS as my Linux install I'd think there would be no difference

The steps for set the compiler path...
Open the setting
  File->Preferences->Settings
![image](https://github.com/QB64Official/vscode/assets/2650021/ed22e3f1-20b2-486b-8139-8c4c7124c94a)

Then filter by QB64 and set the Compiler Path
![image](https://github.com/QB64Official/vscode/assets/2650021/09c3620d-1e8a-4062-8667-2c88a5e74c27)

Also @grymmjack has created a video or 2 on how to use the extension. I they are on YouTube. 
Here's the link to 1 of them  https://www.youtube.com/watch?v=6kn-N_-eycg

**Comment by grymmjack** [comment]
Does QB64PE compile on a Chromebook?

**Comment by LordDurus** [comment]
This has not been updated in a while closing
