### ISSUE TITLE
Release file qb64-0.9.1.vsix does not install in vscode 1.87.2. Fails with 'Corrupt ZIP: end of central directory record signature not found'

### ISSUE THREAD

**Issue by Dowster64** [QB64Official/vscode#135]
Just watching @grymmjack 's great video and following along.  Came across this issue with the file in the title.  Note that qb64-0.9.0.vsix installs fine. Info :Completed installing QB64 extension from VSIX. 
For both files I downloaded them directly from github without cloning the full repo and used the three dot menu (and the pallette menu) to try and install.  Same error with each method.
Working on an old 8052-BASIC microcontroller program and these tools are invaluable,
Thanks!

**Comment by grymmjack** [comment]
Hey @Dowster64 glad you enjoyed the video.

I'm not sure where @LordDurus is at with this project as I haven't spoken to him in a while, but regardless of this...

So the GitHub downloads aren't working, but the vsix sounds like it may be corrupted?

**Comment by suttontools** [comment]
Hi @grymmjack,
Same person different account here!  Thanks for the reply.  I did not want to clone the full repo, I only wanted to use the software, so I only downloaded the two vsix files.  The first (latest version) download did not install in vscode.  It gave the error in the title.  The older version  qb64-0.9.0.vsix installs fine.
I did not try to download the full repo, which I guess is used to build those vsix/zip files?

**Comment by LordDurus** [comment]
I agree with @grymmjack sounds like the down load was corrupted.  I just downloaded the vsix directly and installed in.
![image](https://github.com/QB64Official/vscode/assets/2650021/18889842-8d9b-4b78-bee1-7165672647c1)
![image](https://github.com/QB64Official/vscode/assets/2650021/3aa83fb5-2055-4a96-970b-78e06dc19b98)

VsCode Version
Version: 1.85.0 (user setup)
Commit: af28b32d7e553898b2a91af498b1fb666fdebe0c
Date: 2023-12-06T20:48:09.019Z
Electron: 25.9.7
ElectronBuildId: 25551756
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

Please done try down loading it again.  If that doesn't please post the info about your VSCode.

**Comment by Dowster64** [comment]
@grymmjack and @LordDurus - thanks for your help.  Yes the first download was truncated.  I've just checked.  Actually,  for some reason I downloaded a link for qb64-0.9.1.vsix (not the file) and the actual file for qb64-0.9.0.vsix. I really don't get how I managed to muck that up.  I didn't even check the size of the download until today.   Definitely wasn't firing on all cylinders ...
