### ISSUE TITLE
Create a backup when saving.

### ISSUE THREAD

**Issue by LordDurus** [QB64Official/vscode#18]
Create a *.bak of a QB64 file (bas, bi, bm) when saving.  Only 1 backup per file.

**Comment by DualBrain** [comment]
I like the idea... but please make that an option.  With the ability to utilize `git` this is problematic if combined.  I just experienced this with using the edit feature in WinMerge (which does something very similar) and it is driving me absolutely bonkers.  And it's only doing that within the context of `git`.  

I'm not sure if you could somehow determine if the folder is managed in `git` or not; but if you could that would be an awesome way to present a potential "Auto" setting - Yes, No and Auto would be pretty cool - and, if so, default to "Auto".

**Comment by LordDurus** [comment]
I didn't even think of git good call.
Adding a setting is a good idea (a must really).
If instead of .bak the extension becomes .bak-bas | .bak-bi | bak-bm then I think auto adding to gitignore would be safe.
