### ISSUE TITLE
Opening include containing a subfolder fails.

### ISSUE THREAD

**Issue by DualBrain** [QB64Official/vscode#3]
It appears that the path seen (verified) is working, but when it is being combined in order to open the target file the root path is defaulting to the path used to open VSCode instead of the path of the opened .BAS file.

c:\bas  <- launched VSCode
c:\bas\qbint <- opened file in this folder
c:\bas\qbint\includes <- include file is in this folder

**Comment by LordDurus** [comment]
I've been unable to recreate this issue.
