### ISSUE TITLE
Utilize local QB64 help (markdown) when available.

### ISSUE THREAD

**Issue by DualBrain** [QB64Official/vscode#35]
QB64 will be migrating from .txt files to .md files for local help. These files will be named the same as they are on the wiki (as they will literally duplicated from the wiki).  So would like to see the option of being able to open these within VSCode (F1).  Additionally, would like to have the option, defaulting to enabled (view), for opening in either "view" mode or "edit" mode. I also think that the path should default to these files (under the QB64) folder - but, we should also have the ability to override this path so that, for those that are contributing to the wiki, can point it to a local repo of the actual wiki instead of the files in the QB64 folder.

**Comment by LordDurus** [comment]
This is in v0.6.0.
Play around with and make sure it works how we want.

**Comment by DualBrain** [comment]
Confirming that things appear to be working as envisioned as of v0.6.2!
