### ISSUE TITLE
F1 currently requires that you highlight the word...

### ISSUE THREAD

**Issue by DualBrain** [QB64Official/vscode#4]
... would be nice if it could determine the word that the cursor currently resides and utilize that word when launching help.  Primary reason is as one is typing, navigating with cursor keys, etc. it feels more natural (to me, suspect others) to simply be able to press F1 to go to help instead of having to highlight the word first before doing so.

**Comment by LordDurus** [comment]
Code is completed Planed fore release 0.3.0

**Comment by LordDurus** [comment]
Dine
