### ISSUE TITLE
0.8.0 VSIX - CTRL+Move mouse doing *weird things*.

### ISSUE THREAD

**Issue by DualBrain** [QB64Official/vscode#61]
Hover over a + 1 and you get a "The editor could not be opened due to an unexpected error: File is a directory" in an empty tab and an OK "button".

I'm encountering this because I'm using CTRL+C/CTRL+V/CTRL+X operations while highlighting things with a mouse and it started popping up a lot; I then took a moment to narrow it down to the most minimal repro I could find.  CTRL+move mouse (hover?).  

I did disable "Qb64: Is Hover Text File Enabled" and am still getting this happening (meaning, no difference in behavior).

**Comment by LordDurus** [comment]
This is a know problem.  It's really a VScode problem.

There are 2 ways to work around this problem.
1 Turn hovertext off (I didn't do this).
2 Added "editor.multiCursorModifier": "ctrlCmd" to the setting.json in your vscode folder.

I went with number 2. But that doesn't really fix the problem it just moves to the alt key.

![image](https://user-images.githubusercontent.com/2650021/191108010-d5edf083-fdf2-4d17-87d8-1e5987ec461e.png)
![image](https://user-images.githubusercontent.com/2650021/191108048-9ee63a5e-5acd-4264-966a-2c0946c93cf3.png)

**Comment by LordDurus** [comment]
There is a discussion in the VSCode discord channel about this.
